# Generated by Django 5.0.4 on 2024-04-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projectmanager_project_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
